
version: '3.3'

services:

  yolo:

      image: ivanduque0/antispoofingyolo:V0.1

      container_name: yolo
      
      environment:
         - DISPLAY=unix$DISPLAY
         - HOSTSNAPSHOOT=http://192.168.21.126:8080/?action=snapshot
         - ACCESO=1
         - DATABASE=tesis
         - USERDB=tesis
         - PASSWORD=tesis
         - HOST=192.168.21.141
         - PORT=44

      
      command: python3 codigo/detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.3

      volumes:
         - .:/usr/src/app
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true

# comando= python3 detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.3

# docker run -it -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH -v /home/seguricel/Desktop/YoloV5:/usr/src/app 2eda79ec9e2e python3 detect.py --weights modeloYOLOV5.pt --source http://192.168.21.126:8080/?action=stream

# docker run -it -v /home/seguricel/Desktop/YoloV5:/usr/src/app -e DATABASE=tesis -e HOSTSNAPSHOOT=http://192.168.21.126:8080/?action=snapshot -e ACCESO=1 -e USERDB=tesis -e PASSWORD=tesis -e HOST=192.168.21.141 -e PORT=44 2eda79ec9e2e bash